### ISSUE TITLE
Any document to descript the APIs?

### ISSUE THREAD

**Issue by willson-chen** [nmoinvaz/minizip#445] opened 2020-01-16 12:00 UTC
I am a beginner to minizip. Is there any document or example to describe how to use APIs?

**Comment by nmoinvaz** [comment] 2020-01-17 18:48
Currently I don't have any document that does that. There is some code at the bottom of the Wiki on this GitHub but that is it.

**Comment by willson-chen** [comment] 2020-01-18 14:21
@nmoinvaz , and any plan to accept PR of such document, please?

**Comment by nmoinvaz** [comment] 2020-01-18 18:18
I am willing to accept PR of a document.

**Comment by willson-chen** [comment] 2020-01-19 02:01
@nmoinvaz , hi,

I will try to contribute to the doc. But I need your help when necessary. :)

What about a file named `HowToUse.md`, located under `doc` dir?

Here is the first level subtitle should be included I think:

* What is minizip: s short description.
* Example: one or two simple examples to demonstrate how to use minizip to zip and unzip files.
* API reference: specific the input parameter and return value for each API. Considering the amount of APIs, this part will take a long time.

BTW, do you have other social account so that I could send direct message to ask for help? Is your email in git log avaible? 

Many thanks!

**Comment by nmoinvaz** [comment] 2020-01-19 02:16
That sounds like a good start. In think showing the distrinctions between mz_zip (which can work directly with the archive) and mz_zip_reader/mz_zip_writer (which works with the file system to build or extract the archive) is an important distrinction to make. Also mz_compat is used for the compatibility layer and can also work directly with the archive. Yes I am available via the email on git log. Thanks for your help!

**Comment by willson-chen** [comment] 2020-01-22 12:35
> That sounds like a good start. In think showing the distrinctions between mz_zip (which can work directly with the archive) and mz_zip_reader/mz_zip_writer (which works with the file system to build or extract the archive) is an important distrinction to make. Also mz_compat is used for the compatibility layer and can also work directly with the archive. Yes I am available via the email on git log. Thanks for your help!

I think I need some time to understand the code of minizip.

You are saying, there are **THREE** series of API to zip/unzip archive?
1. mz_zip
2. mz_zip_reader/mz_zip_writer
3. mz_compat

**Comment by nmoinvaz** [comment] 2020-01-22 14:00
Yes that is correct, there are three different APIs. 

- `mz_zip` handles zip archive file format, it allows you direct access the zip entries and their properties.
- `mz_zip_reader`/`mz_zip_writer` is an easier to use interface than `mz_zip` to extract files to disk or compress them. It uses `mz_zip` but it handles all file system handling such as updating a file's last modified time, or enumerating directories to compress all the files. 
- `mz_compat` uses `mz_zip` underneath to provide a minizip 1.x compatibility layer. It operates at the same level as `mz_zip`

**Comment by nmoinvaz** [comment] 2020-02-08 18:06
I think this issue is a duplicate of #426. Please see that issue for further discussion.

**Closed by nmoinvaz** 2020-02-08 18:06 UTC
