### ISSUE TITLE
64 bits vs 32 bits

### ISSUE THREAD

**Issue by magic-tech** [nmoinvaz/minizip#45] opened 2016-02-24 04:41 UTC
Hi, I'm using your lib in my game engine, and yesterday i have tried to unzip a file generated on macosx  (64) on windows 10 (64), but for my surprise it can't open even in winrar, and the file generated on windows doesn't open on linux (64) or macosx (64)...
So i don't know if its a os problem or architecture.
If you guys wanna test it, here are the links:
https://www.dropbox.com/s/l1h1zz5n9ivkdup/data.magic3d
https://www.dropbox.com/s/5s4dlp0qvmytwfd/data.magic3d_windows

My project is https://github.com/magic-tech/Magic3D.git and it is compiled with QT 5.5.1 using mingw32
Thanks in advance.

**Comment by nmoinvaz** [comment] 2016-02-24 14:35
Please uncomment unzip.c @ 534 and see if that fixes it for you.

**Comment by magic-tech** [comment] 2016-02-24 18:31
Unfortunately nothing changed.

If you try open the file, the function unzReadCurrentFile int unzip.c @ 1315 will return -3.

**Comment by nmoinvaz** [comment] 2016-02-27 12:54
Please include the password. Thanks.

**Comment by magic-tech** [comment] 2016-02-27 18:26
Sorry, my bad... the password is "magic3d", and listing files works fine... the problem is extract.

**Comment by nmoinvaz** [comment] 2016-02-28 17:08
Yes something appears to be wrong with the archive or the password. WinRAR can't extract it when I rename it to .zip.

**Comment by magic-tech** [comment] 2016-02-28 21:11
Nice... so the problem is with the archive or the password, nothing is wrong with the library that i used to create it. Thanks for the support!

**Comment by nmoinvaz** [comment] 2016-02-28 22:12
I didn't understand before that the library was used to create both archives. I don't have a mac readily available to be able to debug the issue.

**Comment by fungos** [comment] 2016-02-29 05:32
@nmoinvaz Saying that something appears to be wrong with the archive only proves the bug in minizip, so you may be really interested in this bug report as it will certainly help improve minizip quality.

You can easily debug this on windows using the file "data.magic" (the one that was generated on a mac, no need to you have a mac, just a working debugger). 

I've tested it here on my side with both WinRAR 5.00 (64-bit) and 7-Zip 15.14 (64-bit). The results on my windows 64-bits:
- 7-Zip was able to correctly open (list files) and **extract BOTH** files with the password "magic3d";
- WinRAR was able to open (list files) of both files BUT was unable to extract the file "data.magic3d" with the same password "magic3d". The file "data.magic3d_windows" was correctly extracted though.

From what I've debugged, the problem happens [here](https://github.com/nmoinvaz/minizip/blob/master/unzip.c#L1273-L1285), put a break-point there and compare the execution of unzipping both files, you can see that for some reason s->keys and mostly bizarre the s->pcrc_32_tab are fucked up. This seems to be an issue of bad 32bits<>64bits compatibility.

Hope that this is enough information to help you verify that there is an actual bug in the code and help you get it fixed.

Thank you.

**Comment by fungos** [comment] 2016-02-29 05:41
Not surprisingly the [latest closed issue](https://github.com/nmoinvaz/minizip/issues/46) reported by @TobiasWGDE  seems amazingly similar to this one that may raise a red flag.

**Comment by nmoinvaz** [comment] 2016-02-29 14:52
Maybe I am doing something wrong but I am unable to unzip with the latest version of 7-zip using data.magic3d and the password "magic3d". The user interface may say 100% complete, but it shows errors in the window below, "Wrong password..". 

![capture](https://cloud.githubusercontent.com/assets/1364432/13397906/31da6ac8-deb9-11e5-9dab-aa7b79e4d0eb.PNG)

**Comment by nmoinvaz** [comment] 2016-02-29 15:20
I was able to reproduce the issue when using x64 project configuration for minizip.exe and win32 project configuration for miniunz.exe. I created a password protected file with minizip and tried to extract it using miniunz and it failed. When I used both x64 project configurations it works.

**Comment by nmoinvaz** [comment] 2016-02-29 15:33
I was able to reproduce the issue using x64 project configuration for minizip.exe and win32 project configuration for miniunz.exe. I created a password protected file with minizip and tried to extract it using miniunz and it failed. When I used both x64 project configurations it worked.

**Comment by nmoinvaz** [comment] 2016-02-29 15:33
Actually I was debugging incorrectly. It doesn't matter if the zip file was created with win32 project configuration or x64 configuration, everything works. It is probably an platform issue.

**Comment by fungos** [comment] 2016-02-29 23:20
That is right, I've saw the files and assumed they worked, but yes even 7-zip is not able to extract it.
Nevertheless I was able to extract this same file in a Linux Mint VirtualBox instance, so the issue may well be something related to platform or even compiler.

**Comment by luciocosmo** [comment] 2016-03-04 09:11
Hi all, i have the same exact problem. I can give much more details.

The application which uses minizip works correctly with the same zip archives with password (no aes) generated one year ago. The system unzip utility extracts the files with password correctly on all platform.

Now we switched to ios-arm64 builds, the zips without password works correctly, the zip with passwords gives errors reading files with unzReadCurrentFile (no errors enumerating files).

The same exact problem can be found recompiling on CentOS for 64bit.

I'm using now the current minizip branch, nothing changes.

I'm pretty sure the problem is the implementation in crypt.h, which is called through zdecode macro.

I see as incorrectly ported the functions decrypt_byte(), and maybe update_keys().

static int decrypt_byte(unsigned long* pkeys)
{
    unsigned temp;  /* POTENTIAL BUG:  temp*(temp^1) may overflow in an
                     * unpredictable manner on 16-bit systems; not a problem
                     * with any known compiler so far, though */

    temp = ((unsigned)(*(pkeys+2)) & 0xffff) | 2;
    return (int)(((temp * (temp ^ 1)) >> 8) & 0xff);
}

I tried some adjustments, but I was not lucky.
If anyone have some suggestion I can easily try.

**Comment by luciocosmo** [comment] 2016-03-08 16:45
Hi All, see my patch. In my tests fixes the above problem.

**Comment by fungos** [comment] 2016-03-09 02:03
@luciocosmo your [patch](https://github.com/luciocosmo/minizip/commit/9f8c9b799b379c7a455cb2060334c248675b3730.patch) has too much spacing issues. it is very hard to see what was changed (mainly unzip.c), what was changed in it that is related to this bug?

**Comment by luciocosmo** [comment] 2016-03-09 06:50
Ooops, let me fix it.

**Comment by luciocosmo** [comment] 2016-03-09 07:18
It seems I cant win, my editor does tab substitution.
I’ll retry later today.

What’s better ? I delete myfork ?

**Comment by fungos** [comment] 2016-03-10 00:46
No, what is your editor? It may have a config to change tabs<>spaces. Changing it and saving the may fix, then commit over and it should possible to generate a clean patch.

**Comment by magic-tech** [comment] 2016-03-11 04:35
Nice job @luciocosmo apparently your patch worked... I've tested it and worked both ways... files created on windows were extracted on mac, and files created on mac were extracted on windows.

Unfortunately the files created on MAC before the patch doesn't work anymore (but no problems, the important thing is that now they work everywhere).

If you guys want to try it the files are:
https://dl.dropboxusercontent.com/u/21202284/data.magic3d_mac
https://dl.dropboxusercontent.com/u/21202284/data.magic3d_windows

**Comment by luciocosmo** [comment] 2016-03-11 08:35
> Il giorno 11/mar/2016, alle ore 05:35, MagicTech <notifications@github.com> ha scritto:
> 
> Nice job @luciocosmo apparently your patch worked... I've tested it and worked both ways... files created on windows were extracted on mac, and files created on mac were extracted on windows.
> 
> Unfortunately the files created on MAC before the patch doesn't work anymore (but no problems, the important thing is that now they work everywhere).

Hi nmoinvaz

Wait wait. In my case the change was absolutely necessary to open MANY libraries files from an application which runs on Android and iOS.
GBytes of files were generated on OSX with a tool which embeds minizip (previous version).

So in my case all is working now correctly.

I hope really no problems come out but i tested on a part of the content and it’s working.
To tell the truth I did not still check recompiling for Android… but long and in on 32 bit are the same :| i really not forsee problems :|

L

**Comment by magic-tech** [comment] 2016-03-11 17:28
Let me explain... the file https://www.dropbox.com/s/l1h1zz5n9ivkdup/data.magic3d that was created with minizip without your patch on MACOS doesn't work after your patch, but without your patch it ONLY works on MACOS, on Windows it returns -3 in the function unzReadCurrentFile.

the file https://www.dropbox.com/s/5s4dlp0qvmytwfd/data.magic3d_windows that was created with minizip without your patch on Windows works fine on Windows but doesn't open on MACOS, it returns -3 in the function unzReadCurrentFile. BUT with you patch it  NOW OPENS on MACOS.

AND after your patch all files created (using minizip of course) on MAC or WINDOWS works fine both ways.

Probably before your patch the file https://www.dropbox.com/s/l1h1zz5n9ivkdup/data.magic3d was created wrong because of the size of LONG that may differ on MACOS 64 bits or CLANG may differ from MingW on what happens if you try to convert a LONG to INT and vice versa, and now that is unsigned int the data is write same way on both platforms.

Sorry my poor English and if it is too confuse i can explain again.

**Comment by nmoinvaz** [comment] 2016-03-11 18:00
I have merged the pull request. Thank you everybody!

**Comment by luciocosmo** [comment] 2016-03-11 18:24
Perfectly clear. Makes sense !

Inviato da iPhone

**Closed** 2016-03-11 18:42 UTC
